version: '3'
services:
  db:
    image: postgres
  webpacker:
    build:
        context: .
        dockerfile: docker/Dockerfile
    command: bash -c "./bin/webpack-dev-server"
  web:
    build: .
    command: bash -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
